# /etc/mkinitcpio.conf.d/nssp.conf
# NSSP Lilith OS - mkinitcpio configuration

MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=(/usr/bin/btrfs /usr/sbin/cryptsetup)
FILES=()
HOOKS=(base systemd autodetect microcode modconf kms keyboard sd-vconsole block sd-encrypt btrfs filesystems fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-3)